travis:
  secure:
    BINSTAR_TOKEN: D8wSQ2zRhpMIKk52b43Qb/3RS1NqTzFW25nxqvRczLoDc6le+3PAgAEI7crc6seMh0i1sZlNNeNf0nJkzXZ2HOqPNZv12EOIR3bJgLgPGzgrUxlvYqgDGZidxYNpn03ovHnSv0iOJsdrizKy3Ckbs0GL7JDWuQlbykJ5Vvf68Yh6pBIC80C7bhQy0zswfeDDsK7F1v47y7IkKqkQT2m/uo6EQtj3jHnAvGvpqFy9gTHDGOeXhj7jibFzFuR6+HCqQNx2nqoVfGFvUjKQk79B+7H+SMuAArUxj4cp6SiOhkb3jjZaYugLr7jAjunCIYqmvNYtSb0gDnVhhovAPmo7vycSexA3WZUhGk6IVxNem1IPNbRqksJX81yyH3iwHKI7hQmfu3UY1+MCd83ay+wKotc0OVK77EXM4PA9wFviF/ACS9QTBuAcH1sg5dBpfkDQc2NfKMaHAv7i2BNHwyM2KBDmdH3vrMTQFEeMHOxmiDLWf7f1p/1N5OcEcI7+s7IBQHUEJYIpS65Gn3L4eRyDtdeBSJh3hwfYTZwPLLpxJ3WOrmHApOLyrGcsLe5k9+hD1kfAmBJhKcCZtz+az4Eq8Gkl3F31oQeUCSmuo2OKxh768IOmfuIVRm+4kJuvqGdwWY6mtu+5Vim/sUuDh28HUvvns7h4rf9md6Xl6/PeWi8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
